# Hologram config

# The directory containing the source files to parse
source: ./build

# The directory that hologram will build to
destination: ./public

# The assets needed to build the style guide (includes header.html, footer.html, etc)
documentation_assets: ./style-guide/assets

# This is a custom markdown renderer (see Redcarpet documentation for
# how to do this)
# custom_markdown: trulia_markdown_renderer.rb

# Any other asset folders that need to be copied to the destination folder
# This where you should include your full stylesheets, component javascript,
# libraries and any other dependencies your style guide will have
dependencies:
#  - ./bower_components/
